### ISSUE TITLE
Bug: When adding a new page to our docs, some links are broken on the deploy URL

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/docs#202]
See https://github.com/cloudquery/docs/runs/6953409994?check_suite_focus=true

Seems like there are 2 causes for it:
1. React Helmet references the main host which doesn't have the new page yet:
https://github.com/cloudquery/docs/pull/201#issuecomment-1159637935
![image](https://user-images.githubusercontent.com/26760571/174470362-d2a56e7c-fc3b-4ba9-bed5-243392276831.png)
2. The `Edit this page` on GitHub link references the `main` branch that is missing this file:
![image](https://user-images.githubusercontent.com/26760571/174470372-9c2cd269-2d81-4197-ab7d-f9ff1595513a.png)

### Proposal

1. See if we can tell React Helmet to use the current host
2. Use the branch of the PR for `Edit this page` links

**Comment by dj-stormtrooper** [comment]
here is fix https://github.com/cloudquery/docs/pull/264
