### ISSUE TITLE
Broken/outdated links to docs

### ISSUE THREAD

**Issue by nkabardin** [cloudquery/docs#227]
We have a bunch of broken links in blog to our docs, but it's not very clear how to update them, so help will be appreciated :)

Broken link: https://docs.cloudquery.io/policy/policy
at https://www.cloudquery.io/blog/announcing-cloudquery-policies

Broken link: https://docs.cloudquery.io/docs/cli/drift/overview/
at https://www.cloudquery.io/blog/announcing-cloudquery-policies

Broken link: twice /blog/assets/aws_security_group_view.sql
blog: https://www.cloudquery.io/blog/aws-log4j-and-finding-unrestricted-outbound-access
with this one, asset was probably removed accidentially from cq-website repo, but let's please create docs page?

Broken link: https://github.com/cloudquery/cloudquery/blob/main/example.aws_cis.policy.yml
blog: https://www.cloudquery.io/blog/continuous-aws-iam-security-best-practices

https://www.cloudquery.io/blog/running-cloudquery-in-aws-lambda
redirects to
Broken link:  https://docs.cloudquery.io/docs/deployment/helm-chart/

Broken link: https://docs.cloudquery.io/database-configuration
https://www.cloudquery.io/blog/how-to-aws-cis-compliance

**Comment by bbernays** [comment]
Fixed in https://github.com/cloudquery/cq-website/pull/585
